name: syncToGitee

on:
  push:
    branches: 
      - '*'

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source codes 
      uses: actions/checkout@v2 
    - name: Mirror the Github organization repos to Gitee. 
      uses: Yikun/hub-mirror-action@master  # 使用Yikun/hub-mirror-action
      with:
        src: github/cyezia  # 源端账户名(github)
        dst: gitee/yezi  # 目的端账户名(gitee)
        dst_key: ${{ secrets.DXSECRETRSA }}  # SSH密钥对中的私钥
        dst_token:  ${{ secrets.GITEE_TOKEN }}  # Gitee账户的私人令牌
        static_list: "F2E"  # 静态同步列表，在此填写需要同步的仓库名称，可填写多个
        force_update: true  # 启用后，强制同步，即强制覆盖目的端仓库
        debug: true  # 启用后会显示所有执行命令

      